### ISSUE TITLE
TODO before resubmission

### ISSUE THREAD

**Issue by kdorheim** [kdorheim/Dorheim_etal_2023_GMD#7]
- [ ] replace link in the manuscript 
- [ ] create new zenodo file /release here
- [ ] update the Hector version to the V3.2 release 
- [ ] new release of the hector cmip6 data
